runtime: nodejs18
instance_class: F2
env: standard
handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
- url: /build
  static_dir: public/build
- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
