name: Deploy to GAE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GAE
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > ${GITHUB_WORKSPACE}/key.json
        gcloud auth activate-service-account --key-file=${GITHUB_WORKSPACE}/key.json
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud app deploy --quiet
